version: "3"
services:
  db:
    image: postgis/postgis:16-master
    container_name: sisvetor-db
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - /opt/backups:/opt/backups
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
    networks:
      - sisvetor-network

networks:
  sisvetor-network:
    external: true

volumes:
  pgdata:
